### ISSUE TITLE
Dispatch breaks when keyword used for normal arg

### ISSUE THREAD

**Issue by Moosems** [beartype/plum#164]
```python
from plum import dispatch


class foo:
    def __init__(self) -> None:
        pass

    @dispatch
    def bar(self, arg: str) -> None:
        print(arg)


spam = foo()
spam.bar("test")  # Works just fine
# spam.bar(arg="test")  # Uncomment and it breaks
```

**Comment by PhilipVinc** [comment]
https://beartype.github.io/plum/keyword_arguments.html

**Comment by Moosems** [comment]
I see. I personally disagree with the reasoning given (the x, y example) and think that should fail but that may just be me. Closing issue :)

**Comment by PhilipVinc** [comment]
What do you mean just fail? It does fail…

**Comment by Moosems** [comment]
> What might be confusing is what f(x=1.0, y=1) would do

I wouldn't expect that to be valid

**Comment by PhilipVinc** [comment]
I can't really follow what you're trying to say.

However, if what you're saying is that the example given there should not be valid, the logic that follows is usually that you cannot dispatch on keyword arguments in general, otherwise there would be a lot of edge cases.

As far as I know, there are no 'correct' formal multiple dispatch logic that handle keyword argument names as well as types that were discussed in the literature (while several that handle positional arguments do exist).

It's probably not an unsolvable problem. Just an hard one that I can't find a solution for.
